### ISSUE TITLE
v5 upgrade error: Expected signal to be an instanceof AbortSignal

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok-js-client#340]
## Expected Behavior

Any fetch of story should be resolved.

After upgrade to v5: 

```
Expected signal to be an instanceof AbortSignal
    at new Request (/node_modules/next/dist/compiled/node-fetch/index.js:1:62408)
    at /node_modules/next/dist/compiled/node-fetch/index.js:1:65037
    at new Promise (<anonymous>)
```

## Current Behavior

Can't fetch any story with the storyblok-js-client

## Steps to Reproduce

Upgrade codebase from v4 => v5

**Comment by dohomi** [comment]
@thiagosaife I am using NextJS on Vecel, that is bound to the versions of AWS lambda (https://vercel.com/docs/concepts/functions/serverless-functions/runtimes/node-js#node.js-version). Shouldn't this be polyfilled within `storyblok-js-client` as that is the reason of throwing the error?

**Comment by dohomi** [comment]
I tried Node v18 LTS and the error disappears. But that would prevent any NextJS user to use this library in their application (if they run it on Vercel).
Maybe instead of isomorphic-fetch either [cross-fetch](https://www.npmjs.com/package/cross-fetch) or [whatwg-fetch](https://www.npmjs.com/package/whatwg-fetch) are better solutions as isomorphic-fetch seems not to be actively maintained.
