### ISSUE TITLE
Updating Datasource Entry dimension error ends up with error related to probably JSON.parse of empty response

### ISSUE THREAD

**Issue by marckraw** [storyblok/storyblok-js-client#400]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client

[![storyblok.com](https://a.storyblok.com/f/88751/1776x360/4d075611c6/sb-js-sdk.png)][storyblokurl]

tested on `storyblok-js-client: 5.2.5`

Updating Datasource Entry dimension value via `storyblok-js-client` is working, but the stuff returned is raising error, becasue there is no content of the response (status: 204 no content in postman), but I think, `storyblokClient` is trying to `JSON.parse` it which end with this error: 
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Response.json (node:internal/deps/undici/undici:6160:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async J._responseHandler (file:///Users/marckraw/Projects/OpenSource/sb-mig/node_modules/storyblok-js-client/dist/index.mjs:276:5)
    at async J._methodHandler (file:///Users/marckraw/Projects/OpenSource/sb-mig/node_modules/storyblok-js-client/dist/index.mjs:300:17)
```

postman with no content status below:
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/8228270/210452429-5cf87ff6-d68d-4311-b7f9-b2bdebd07be8.png">

---

## Expected Behavior

To NOT raise error and potentially return, the same as just creating or updating Datasource entry - so return something like that: 
```
{
    datasource_entry: {
      id: 3992481,
      name: 'Alerts/Warning',
      value: 'green',
      dimension_value: 'changed-dimension-value'
    }
  },
```

## Steps to Reproduce

1. Just create empty project with newest version of `storyblok-js-client`
2. make request to update datasource entry, but to update its dimension value

**Comment by marckraw** [comment]
upd: seems like it is happening for any `PUT` request to update `datasource entry`

**Comment by marckraw** [comment]
@thiagosaife I think it was working on version 4, but also, i added a lot of new functionalities to it, in terms of handling datasources, so i'm not 100% sure if i used the same requests previously. 

sample request that ends up with eror stated in the issue description
```
return sbApi
        .put(`spaces/${spaceId}/datasource_entries/${datasourceEntry.id}`, {
            datasource_entry: finalDatasource_entry,
        } as any)
        .then((data: any) => {
            console.log(data)
            return data;
        })
        .catch((err) => {
            Logger.error(err);
        });
```

if i try to log data, than this error occurs, if i'm not `console.log` it, error will not raise.

**Comment by patrykkurzeja91** [comment]
I just installed `@storyblok/nuxt: 5.0.0` and noticed similar issue with datasources.
Standard GET call
```
const { data } = await storyblokApi.get(
  'cdn/datasource_entries?datasource=global-values',
)
```
gives me some random datasource values instead of ones I asked for (as slug is specified `global-values`)

**Comment by ademarCardoso** [comment]
@marckraw Thanks for the information, I opened a PR with the correction of this problem, soon it will be in production

**Comment by ademarCardoso** [comment]
@patrykkurzeja91 I'll check if this filter is working correctly, thanks for the report friend.

I'll be back with information as soon as possible.
